# Generated by Django 2.0.4 on 2018-04-26 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamqa',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentexamqa',
            name='student_exam',
        ),
        migrations.AddField(
            model_name='studentexamqa',
            name='exam',
            field=models.ManyToManyField(to='exam_management.Exam'),
        ),
        migrations.AddField(
            model_name='studentexamqa',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
